config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
    respond_to do |format|
      format.html { render :welcome }
    end
  end

  def about
    respond_to do |format|
      format.html { render :about }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dep</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>

 <h2>Software Review and Discussion</h2>

 










 

 <p><%= link_to 'Welcome', welcome_path %></p>

app/views/static_pages/welcome.html.erb
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <h2>Dep design & photography</h2>

        <%= image_tag "QO5A7309.jpg", height: 500 %>

 <p> Hi, We are Dep, international fine art wedding photographers</p>

 <ul>
   <li>We are locacte in Memphis and server around the world</li>
   <li>We are passionate in wedding photography</li>
   <li>We are honor to provide you with the best services</li>
 </ul>

 <p>
   A picture is worth a thousand words, but a true photograph is a moment forever captured in time. It’s a still image that tells a story of love, fear, wanting and need. I’ve always been a story teller, using the light and color seized through my camera lens. That still image is bond between myself and my subject, and with each snap of the shutter, that piece of glass fades away into a shared experience between us.
 </p>
    </body>


    <p>
   Find more about Dep  <%= link_to "here", "https://www.instagram.com/depweddingphotos/", target: "_blank" %> 
 </p>

  <p><%= link_to "About", about_path %></p>
</html>